import{s as k,a as d,i as n}from"./assets/vendor-dbdbd0f5.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerpolicy&&(o.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?o.credentials="include":e.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const R=document.querySelector(".form"),f=document.querySelector(".input"),h=document.querySelector(".gallery"),b=document.querySelector(".loader-more-btn"),p=document.querySelector(".loader"),u=document.querySelector(".button-load-more");y();const H="41813550-341719f2cbf02751aeba3ddbd";let c="",l=1;const m=40;let S=new k(".gallery a",{captionDelay:250,captionsData:"alt"});const w=()=>new URLSearchParams({key:H,q:c,image_type:"photo",orientation:"horizontal",safesearch:!0,page:l,per_page:m});d.defaults.baseURL="https://pixabay.com";const L="/api/";R.addEventListener("submit",async r=>{if(r.preventDefault(),l=1,$(),y(),c=f.value.trim(),c==="")return n.info({timeout:5e3,title:"info",message:"Sorry, but you need to write at least one character!",position:"topRight"});I(),f.value="";try{const t=await d.get(L,{params:w()});B();const s=t.data;s.hits.length===0&&n.error({timeout:5e3,title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),v(s.hits),s.hits.length>=m&&O(),S.refresh()}catch(t){p.style.display="none",n.error({timeout:5e3,title:"Error",message:t.message,position:"topRight"}),console.error("Error when receiving data:",t)}});u.addEventListener("click",async()=>{D(),l+=1;try{const r=await d.get(L,{params:w()});g();const t=r.data;l>=Math.ceil(t.totalHits/m)&&(y(),n.error({timeout:5e3,title:"Error",message:"You've reached the end of search results",position:"topRight"})),v(t.hits),P(),S.refresh()}catch(r){g(),n.error({timeout:5e3,title:"Error",message:r.message,position:"topRight"}),console.error("Error fetching more data:",r)}});const P=()=>{const t=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:t*3,behavior:"smooth"})},$=()=>{h.innerHTML=""};function I(){p.style.display="block"}function B(){p.style.display="none"}function D(){b.style.display="block"}function g(){b.style.display="none"}function O(){u.style.display="block"}function y(){u.style.display="none"}function v(r){const t=r.reduce((s,{webformatURL:i,largeImageURL:e,tags:o,likes:a,views:q,comments:M,downloads:E})=>s+`<li class="gallery-item">
          <a href="${e}">
           <img class="gallery-image" src="${i}" alt="${o}"
           />
          </a>         
          <div class="card-container">
            <p class="p-item">Likes:<span class="span-item">${a}</span></p>
            <p>Views:<span class="span-item">${q}</span></p>
            <p>Comments:<span class="span-item">${M}</span></p>
            <p>Downloads:<span class="span-item">${E}</span></p>
          </div> 
        </li>`,"");h.insertAdjacentHTML("beforeend",t)}
//# sourceMappingURL=commonHelpers.js.map
